name: Publish RevBayes Docker images

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          path: main
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: checkout revbayes
        uses: actions/checkout@v2 
        with: 
          repository: revbayes/revbayes
          path: revbayes
      - name: build the image
        run: |
          docker buildx bake -f main/docker-compose.yml --progress plain
