name: Publish RevBayes Docker images

on:
    push:
      branches: master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: clone revbayes 
        run: |
          git clone https://github.com/revbayes/revbayes.git /revbayes 
      - name: build the image
        run: |
          docker buildx bake -f docker-compose.yml --progress plain