name: Publish RevBayes Docker images

on:
  push:
    branches:
     - "*"
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: checkout code
        uses: actions/checkout@v2
      - name: Build and Publish
        run: |
          docker buildx bake -f docker-compose.yml --progress plain --push
